apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reports_analytics
  namespace: staging
spec:
  host: reports_analytics
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
