apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-cred-helper
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-cred-helper
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-cred-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-cred-helper
subjects:
- kind: ServiceAccount
  name: ecr-cred-helper
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: kube-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "PLACEHOLDER"
  AWS_SECRET_ACCESS_KEY: "PLACEHOLDER"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-cred-helper
  namespace: kube-system
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: ecr-cred-helper
          restartPolicy: OnFailure
          containers:
          - name: ecr-cred-helper
            image: amazon/aws-cli:latest
            env:
            - name: REGION
              value: "us-east-1"
            - name: ACCOUNT_ID
              value: "024955634588"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -e
              
              echo "Getting ECR authorization token..."
              TOKEN=$(aws ecr get-login-password --region ${REGION})
              
              # Create aws-ecr-cred in staging namespace
              echo "Creating aws-ecr-cred in staging namespace..."
              kubectl delete secret aws-ecr-cred -n staging --ignore-not-found
              kubectl create secret docker-registry aws-ecr-cred \
                --docker-server=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${TOKEN}" \
                --namespace=staging
              
              # Create aws-ecr-cred in production namespace
              echo "Creating aws-ecr-cred in production namespace..."
              kubectl delete secret aws-ecr-cred -n production --ignore-not-found
              kubectl create secret docker-registry aws-ecr-cred \
                --docker-server=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${TOKEN}" \
                --namespace=production
              
              echo "ECR credentials refreshed successfully!"
