apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service_management
  namespace: staging
spec:
  host: service_management
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
