apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-credential-helper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WSO2-G02/salon-gitops
    path: staging
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
