apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-service-management
spec:
  project: default
  source:
    repoURL: https://github.com/WSO2-G02/salon-gitops
    path: production/service_management
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      