# =============================================================================
# Istio Gateway for Aurora Glam Salon
# =============================================================================
# This gateway accepts traffic for all salon domains.
# VirtualServices in each namespace handle routing based on the Host header.
#
# Domains:
#   - aurora-glam.com         → Production namespace
#   - staging.aurora-glam.com → Staging namespace
#   - argocd.aurora-glam.com  → ArgoCD namespace
#   - grafana.aurora-glam.com → Monitoring (Grafana)
#
# TLS/HTTPS: Currently using HTTP. For HTTPS, add TLS configuration
# with certificates from AWS Certificate Manager.
# =============================================================================
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: salon-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "aurora-glam.com"
    - "staging.aurora-glam.com"
    - "argocd.aurora-glam.com"
    - "grafana.aurora-glam.com"
